name: CI - Build and Push Docker Image

on:
  push:
    branches: [madhan]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Tag
        id: set_tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Debug Docker tag
        run: echo "Image Tag:${{ steps.set_tag.outputs.tag }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi-backend:${{ steps.set_tag.outputs.tag }} ./my-strapi
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-backend:${{ steps.set_tag.outputs.tag }}

      - name: Trigger CD workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: CD - Terraform Deploy to EC2
          ref: madhan
          inputs:
            image_tag:"${{ steps.set_tag.outputs.tag }}"
