name: CD - Terraform Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: 'Docker image tag to deploy'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply \
            -var-file="envs/dev.tfvars" \
            -var="image_tag=${{ github.event.inputs.image_tag }}" \
            -auto-approve
          echo "EC2_IP=$(terraform output -raw strapi_public_ip)" >> $GITHUB_ENV

      - name: Wait for EC2 to boot
        run: sleep 60

      - name: Print Strapi URL
        run: echo "✅ Strapi deployed at http://${{ env.EC2_IP }}:1337"
