name: CD - Terraform Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

concurrency:
  group: terraform-deploy
  cancel-in-progress: true

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Confirm image tag file exists
        run: cat image_tag.txt

      - name: Read image tag from file
        id: read_tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply \
            -var-file="envs/dev.tfvars" \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -auto-approve
          echo "EC2_IP=$(terraform output -raw strapi_public_ip)" >> $GITHUB_ENV

      - name: Wait for EC2 to become ready
        run: |
          echo "Waiting for EC2 to boot..."
          sleep 60

      - name: Print Strapi URL
        run: echo "✅ Strapi deployed at http://${{ env.EC2_IP }}:1337"
